/* eslint-disable @typescript-eslint/no-unused-vars */

import Carrito from "../../components/public/utils/Carrito";
import { Header } from "../../components/public/estructura/Header";
import { Footer } from "../../components/public/estructura/Footer";

/*
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})
*/
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({
  children,
  components, // Recíbelo para cumplir con la interfaz
  params, // También se recibe, aunque sea opcional
}: {
  children?: React.ReactNode;
  components: React.ReactNode;
  params?: Promise<{ [key: string]: string }>; // Ajusta el tipo si es necesario
}) {
  return (
    <>
      <Header />
      <Carrito />
      {children}
      <Footer />
    </>
  );
}
